# Combine and Create Datasets

In [1]:
# Get dependencies
import pandas as pd

In [2]:
# Read CSV of county population data
county_pops = pd.read_csv("data/ca-co-pop2010-2019.csv")
county_pops.head()

,Unnamed: 0,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,California,"37,253,956","37,254,519","37,319,502","37,638,369","37,948,800","38,260,787","38,596,972","38,918,045","39,167,117","39,358,497","39,461,588","39,512,223"
1,"Alameda County, California","1,510,271","1,510,258","1,512,986","1,530,915","1,553,764","1,579,593","1,607,792","1,634,538","1,650,950","1,660,196","1,666,756","1,671,329"
2,"Alpine County, California","1,175","1,175","1,161","1,093","1,110","1,128","1,080","1,077","1,047","1,111","1,089","1,129"
3,"Amador County, California","38,091","38,091","37,886","37,543","37,104","36,620","36,726","37,031","37,429","38,529","39,405","39,752"
4,"Butte County, California","220,000","220,005","219,949","219,975","220,869","221,641","223,516","224,631","226,231","228,696","230,339","219,186"

In [3]:
# Rename county column
county_pops = county_pops.rename(columns={"Unnamed: 0": "County"})

# Get county names and population estimates for 2011 and 2016
county_2011_2016 = pd.DataFrame(county_pops[["County", "2011", "2016"]])
county_2011_2016.head()

                       County        2011        2016
0                  California  37,638,369  39,167,117
1  Alameda County, California   1,530,915   1,650,950
2   Alpine County, California       1,093       1,047
3   Amador County, California      37,543      37,429
4    Butte County, California     219,975     226,231

In [4]:
# Remove "County, California" from the County column

for index, row in county_2011_2016.iterrows():
    county = row["County"]
    county_split = county.split(" County")
    #new_county = county_split[0]
    #print("County:" + new_county)
    county_2011_2016.loc[index, "County"] = str(county_split[0])
        
county_2011_2016

             County        2011        2016
0        California  37,638,369  39,167,117
1           Alameda   1,530,915   1,650,950
2            Alpine       1,093       1,047
3            Amador      37,543      37,429
4             Butte     219,975     226,231
5         Calaveras      45,160      45,322
6            Colusa      21,323      21,496
7      Contra Costa   1,065,440   1,137,268
8         Del Norte      28,443      27,382
9         El Dorado     180,936     185,976
10           Fresno     939,406     976,830
11            Glenn      28,139      27,840
12         Humboldt     135,243     136,290
13         Imperial     175,786     180,179
14             Inyo      18,392      17,922
15             Kern     847,970     880,856
16            Kings     151,868     149,382
17             Lake      64,251      63,903
18           Lassen      34,246      30,721
19      Los Angeles   9,876,482  10,105,708
20           Madera     151,675     153,956
21            Marin     255,376     260,562
22         Mariposa      18,170      17,456
23        Mendocino      87,334      87,285
24           Merced     259,297     267,628
25            Modoc       9,509       8,961
26             Mono      14,422      14,273
27         Monterey     420,456     433,953
28             Napa     137,691     140,840
29           Nevada      98,701      98,913
30           Orange   3,049,271   3,164,986
31           Placer     356,328     378,943
32           Plumas      19,719      18,665
33        Riverside   2,234,070   2,380,081
34       Sacramento   1,433,730   1,510,987
35       San Benito      55,977      59,225
36   San Bernardino   2,060,827   2,131,960
37        San Diego   3,137,156   3,306,089
38    San Francisco     815,650     871,512
39      San Joaquin     694,354     732,809
40  San Luis Obispo     271,058     281,803
41        San Mateo     728,344     767,906
42    Santa Barbara     425,453     444,340
43      Santa Clara   1,812,054   1,928,368
44       Santa Cruz     264,858     274,396
45           Shasta     177,588     178,571
46           Sierra       3,098       2,951
47         Siskiyou      44,615      43,376
48           Solano     416,342     438,858
49           Sonoma     487,421     502,547
50       Stanislaus     517,560     539,255
51           Sutter      94,482      95,742
52           Tehama      63,331      63,453
53          Trinity      13,685      12,828
54           Tulare     446,784     459,235
55         Tuolumne      54,830      53,770
56          Ventura     830,099     847,323
57             Yolo     201,954     215,627
58             Yuba      72,489      74,952

In [5]:
# Save dataset to CSV
county_2011_2016.to_csv("data/county_2011_2016.csv", index=False)

## Fast Food Data

In [6]:
# Read deprecated county data
county_data = pd.read_csv("data/county_2011_2016.csv")
county_data.head()

       County        2011        2016
0  California  37,638,369  39,167,117
1     Alameda   1,530,915   1,650,950
2      Alpine       1,093       1,047
3      Amador      37,543      37,429
4       Butte     219,975     226,231

In [7]:
# Grab county name (except "California" row), remove spaces, and create list of county names
counties = []

for index, row in county_data.iterrows():
    county = row["County"]
    # Remove spaces and add to list
    if county != "California":
        counties.append(county.replace(" ",""))
counties

['Alameda',
 'Alpine',
 'Amador',
 'Butte',
 'Calaveras',
 'Colusa',
 'ContraCosta',
 'DelNorte',
 'ElDorado',
 'Fresno',
 'Glenn',
 'Humboldt',
 'Imperial',
 'Inyo',
 'Kern',
 'Kings',
 'Lake',
 'Lassen',
 'LosAngeles',
 'Madera',
 'Marin',
 'Mariposa',
 'Mendocino',
 'Merced',
 'Modoc',
 'Mono',
 'Monterey',
 'Napa',
 'Nevada',
 'Orange',
 'Placer',
 'Plumas',
 'Riverside',
 'Sacramento',
 'SanBenito',
 'SanBernardino',
 'SanDiego',
 'SanFrancisco',
 'SanJoaquin',
 'SanLuisObispo',
 'SanMateo',
 'SantaBarbara',
 'SantaClara',
 'SantaCruz',
 'Shasta',
 'Sierra',
 'Siskiyou',
 'Solano',
 'Sonoma',
 'Stanislaus',
 'Sutter',
 'Tehama',
 'Trinity',
 'Tulare',
 'Tuolumne',
 'Ventura',
 'Yolo',
 'Yuba']

In [8]:
# The fast food data is not structured how we want, so we need to make sure it is
# Open the first CSV to use the first column to become the headers of our data frame
Alameda_fast_food = pd.read_csv(f"data/FastFood/Alameda.csv")
columns = Alameda_fast_food["State"].tolist()
columns

['County',
 'Fast-food restaurants, 2011',
 'Fast-food restaurants, 2016',
 'Fast-food restaurants (% change), 2011-16',
 'Fast-food restaurants/1,000 pop, 2011',
 'Fast-food restaurants/1,000 pop, 2016',
 'Fast-food restaurants/1,000 pop (% change), 2011-16',
 'Full-service restaurants, 2011',
 'Full-service restaurants, 2016',
 'Full-service restaurants (% change), 2011-16',
 'Full-service restaurants/1,000 pop, 2011',
 'Full-service restaurants/1,000 pop, 2016',
 'Full-service restaurants/1,000 pop (% change), 2011-16',
 'Expenditures per capita, fast food, 2007*',
 'Expenditures per capita, fast food, 2012*',
 'Expenditures per capita, restaurants, 2007*',
 'Expenditures per capita, restaurants, 2012*']

In [9]:
# Create data frame for fast food data using columns from above
#fast_food_data = pd.DataFrame(columns=columns)
#fast_food_data

In [10]:
# Create fast_food_data dataframe
fast_food_data = pd.DataFrame({"State": columns})

# Use county names to create a loop to open all the fast food CSV files and convert into one dataset

for county in counties:
    # Read county fast food file
    data_file = f"data/FastFood/{county}.csv"
    county_fast_food_data = pd.read_csv(data_file)
    
    # Merge fast_food_data dataframe with fast_food_data
    fast_food_data = fast_food_data.merge(county_fast_food_data, how="outer", on="State")

# Drop index
fast_food_data = fast_food_data.set_index("State")

# Transpose columns and rows
fast_food_data = fast_food_data.T

# Print data frame
fast_food_data

State,County,"Fast-food restaurants, 2011","Fast-food restaurants, 2016","Fast-food restaurants (% change), 2011-16","Fast-food restaurants/1,000 pop, 2011","Fast-food restaurants/1,000 pop, 2016","Fast-food restaurants/1,000 pop (% change), 2011-16","Full-service restaurants, 2011","Full-service restaurants, 2016","Full-service restaurants (% change), 2011-16","Full-service restaurants/1,000 pop, 2011","Full-service restaurants/1,000 pop, 2016","Full-service restaurants/1,000 pop (% change), 2011-16","Expenditures per capita, fast food, 2007*","Expenditures per capita, fast food, 2012*","Expenditures per capita, restaurants, 2007*","Expenditures per capita, restaurants, 2012*"
CA_x,Alameda,1090,1293,18.623853,0.711388,0.782102,9.940291,1401,1560,11.349036,0.914363,0.943604,3.198009,761.447125,642.487457,755.587505,750.318646
CA_y,Alpine,2,0,-100,1.829826,0,-100,3,1,-66.666667,2.744739,0.946074,-65.531378,761.447125,642.487457,755.587505,750.318646
CA_x,Amador,12,21,75,0.319668,0.560403,75.308222,39,44,12.820513,1.03892,1.174179,13.01922,761.447125,642.487457,755.587505,750.318646
CA_y,Butte,147,158,7.482993,0.668173,0.697495,4.388394,125,132,5.6,0.568174,0.582717,2.559615,761.447125,642.487457,755.587505,750.318646
CA_x,Calaveras,26,30,15.384615,0.575692,0.662032,14.997581,39,41,5.128205,0.863539,0.904778,4.775574,761.447125,642.487457,755.587505,750.318646
CA_y,Colusa,16,8,-50,0.748853,0.3696,-50.644491,10,11,10,0.468033,0.508201,8.582121,761.447125,642.487457,755.587505,750.318646
CA_x,Contra Costa,599,701,17.028381,0.561818,0.615644,9.580732,686,757,10.349854,0.643417,0.664825,3.327225,761.447125,642.487457,755.587505,750.318646
CA_y,Del Norte,15,10,-33.333333,0.527296,0.364299,-30.911961,16,24,50,0.562449,0.874317,55.448087,761.447125,642.487457,755.587505,750.318646
CA_x,El Dorado,97,110,13.402062,0.535986,0.590534,10.177258,165,202,22.424242,0.911728,1.084436,18.942875,761.447125,642.487457,755.587505,750.318646
CA_y,Fresno,569,634,11.42355,0.605087,0.647247,6.967445,490,519,5.918367,0.521077,0.529844,1.682429,761.447125,642.487457,755.587505,750.318646
CA_x,Glenn,12,15,25,0.426136,0.536346,25.862624,16,18,12.5,0.568182,0.643616,13.276361,761.447125,642.487457,755.587505,750.318646
CA_y,Humboldt,95,97,2.105263,0.70246,0.710888,1.199816,130,142,9.230769,0.961261,1.040682,8.262135,761.447125,642.487457,755.587505,750.318646
CA_x,Imperial,81,103,27.160494,0.459817,0.569124,23.771749,78,70,-10.25641,0.442787,0.386783,-12.648019,761.447125,642.487457,755.587505,750.318646
CA_y,Inyo,13,15,15.384615,0.706483,0.831762,17.732744,29,27,-6.896552,1.576001,1.497172,-5.001855,761.447125,642.487457,755.587505,750.318646
CA_x,Kern,528,603,14.204545,0.622079,0.68129,9.518227,400,443,10.75,0.471272,0.500516,6.205437,761.447125,642.487457,755.587505,750.318646
CA_y,Kings,90,89,-1.111111,0.591988,0.594137,0.36301,46,45,-2.173913,0.302572,0.300407,-0.715635,761.447125,642.487457,755.587505,750.318646
CA_x,Lake,30,33,10,0.466759,0.516028,10.55559,46,46,0,0.715697,0.719312,0.505082,761.447125,642.487457,755.587505,750.318646
CA_y,Lassen,13,15,15.384615,0.379629,0.484747,27.689722,18,11,-38.888889,0.52564,0.355481,-32.37174,761.447125,642.487457,755.587505,750.318646
CA_x,Los Angeles,7211,8264,14.60269,0.729415,0.814142,11.615733,7125,8113,13.866667,0.720716,0.799266,10.898892,761.447125,642.487457,755.587505,750.318646
CA_y,Madera,75,78,4,0.493824,0.503336,1.926255,48,52,8.333333,0.316047,0.335557,6.173182,761.447125,642.487457,755.587505,750.318646
CA_x,Marin,171,189,10.526316,0.669263,0.722665,7.979239,302,313,3.642384,1.181973,1.196794,1.253947,761.447125,642.487457,755.587505,750.318646
CA_y,Mariposa,9,8,-11.111111,0.495213,0.456517,-7.814045,12,13,8.333333,0.660284,0.74184,12.351632,761.447125,642.487457,755.587505,750.318646
CA_x,Mendocino,52,54,3.846154,0.59519,0.616375,3.559302,106,111,4.716981,1.213273,1.266993,4.427724,761.447125,642.487457,755.587505,750.318646
CA_y,Merced,127,143,12.598425,0.489201,0.53184,8.715995,75,91,21.333333,0.288898,0.338443,17.149721,761.447125,642.487457,755.587505,750.318646
CA_x,Modoc,7,3,-57.142857,0.735681,0.335533,-54.391487,9,8,-11.111111,0.945875,0.894755,-5.404566,761.447125,642.487457,755.587505,750.318646
CA_y,Mono,18,21,16.666667,1.256194,1.489256,18.553058,38,34,-10.526316,2.651965,2.411177,-9.07961,761.447125,642.487457,755.587505,750.318646
CA_x,Monterey,246,264,7.317073,0.584098,0.605001,3.57861,334,380,13.772455,0.793044,0.870835,9.809115,761.447125,642.487457,755.587505,750.318646
CA_y,Napa,76,82,7.894737,0.551104,0.578896,5.042914,134,150,11.940299,0.971683,1.058956,8.981545,761.447125,642.487457,755.587505,750.318646
CA_x,Nevada,53,65,22.641509,0.536905,0.656214,22.22178,98,96,-2.040816,0.992767,0.969178,-2.376073,761.447125,642.487457,755.587505,750.318646
CA_y,Orange,2575,3025,17.475728,0.843304,0.951945,12.882804,2452,2791,13.825449,0.803022,0.878307,9.375238,761.447125,642.487457,755.587505,750.318646
CA_x,Placer,274,334,21.89781,0.768702,0.879545,14.419435,297,328,10.43771,0.833228,0.863744,3.662407,761.447125,642.487457,755.587505,750.318646
CA_y,Plumas,13,9,-30.769231,0.659363,0.479055,-27.345832,39,40,2.564103,1.978089,2.129132,7.635804,761.447125,642.487457,755.587505,750.318646
CA_x,Riverside,1331,1541,15.777611,0.595289,0.64571,8.469984,1089,1211,11.202938,0.487054,0.507433,4.184054,761.447125,642.487457,755.587505,750.318646
CA_y,Sacramento,937,1075,14.727855,0.653187,0.710387,8.757118,892,981,9.977578,0.621817,0.648269,4.254058,761.447125,642.487457,755.587505,750.318646
CA_x,San Benito,26,28,7.692308,0.464004,0.471897,1.701033,28,36,28.571429,0.499697,0.606725,21.41858,761.447125,642.487457,755.587505,750.318646
CA_y,San Bernardino,1346,1526,13.372957,0.652644,0.714041,9.407534,953,1101,15.529906,0.462087,0.515177,11.489039,761.447125,642.487457,755.587505,750.318646
CA_x,San Diego,2348,2736,16.524702,0.747826,0.824792,10.291937,2355,2593,10.106157,0.750056,0.781683,4.216712,761.447125,642.487457,755.587505,750.318646
CA_y,San Francisco,753,958,27.224436,0.922462,1.093479,18.539194,1764,1917,8.673469,2.160986,2.188099,1.254648,761.447125,642.487457,755.587505,750.318646
CA_x,San Joaquin,401,466,16.209476,0.576919,0.634623,10.002039,352,391,11.079545,0.506423,0.532484,5.146128,761.447125,642.487457,755.587505,750.318646
CA_y,San Luis Obispo,219,234,6.849315,0.807671,0.828958,2.635633,312,340,8.974359,1.150655,1.204469,4.676874,761.447125,642.487457,755.587505,750.318646
CA_x,San Mateo,501,593,18.363273,0.687222,0.770569,12.128123,742,828,11.590296,1.017802,1.075938,5.711933,761.447125,642.487457,755.587505,750.318646
CA_y,Santa Barbara,286,344,20.27972,0.67127,0.770789,14.825446,388,408,5.154639,0.910674,0.914191,0.386235,761.447125,642.487457,755.587505,750.318646
CA_x,Santa Clara,1288,1544,19.875776,0.710107,0.799348,12.567269,1555,1712,10.096463,0.85731,0.886323,3.384174,761.447125,642.487457,755.587505,750.318646
CA_y,Santa Cruz,171,175,2.339181,0.645032,0.63591,-1.414178,242,278,14.876033,0.912853,1.010189,10.662877,761.447125,642.487457,755.587505,750.318646
CA_x,Shasta,133,122,-8.270677,0.748895,0.682426,-8.875624,112,118,5.357143,0.630648,0.660051,4.662321,761.447125,642.487457,755.587505,750.318646
CA_y,Sierra,1,1,0,0.322581,0.337382,4.588394,2,4,100,0.645161,1.349528,109.176788,761.447125,642.487457,755.587505,750.318646
CA_x,Siskiyou,29,28,-3.448276,0.65002,0.643515,-1.000698,50,45,-10,1.120724,1.034221,-7.718508,761.447125,642.487457,755.587505,750.318646
CA_y,Solano,270,290,7.407407,0.648023,0.658615,1.634526,243,265,9.053498,0.583221,0.601838,3.192143,761.447125,642.487457,755.587505,750.318646
CA_x,Sonoma,273,291,6.593407,0.55963,0.577572,3.20604,488,523,7.172131,1.000365,1.038042,3.766374,761.447125,642.487457,755.587505,750.318646
CA_y,Stanislaus,327,366,11.926606,0.631233,0.676084,7.105322,255,293,14.901961,0.492246,0.541236,9.952512,761.447125,642.487457,755.587505,750.318646
CA_x,Sutter,51,59,15.686275,0.53934,0.614212,13.882177,51,54,5.882353,0.53934,0.56216,4.231145,761.447125,642.487457,755.587505,750.318646
CA_y,Tehama,34,33,-2.941176,0.536726,0.520144,-3.08957,31,40,29.032258,0.489368,0.630477,28.83498,761.447125,642.487457,755.587505,750.318646
CA_x,Trinity,12,6,-50,0.877385,0.467326,-46.736506,9,13,44.444444,0.658039,1.01254,53.872316,761.447125,642.487457,755.587505,750.318646
CA_y,Tulare,215,264,22.790698,0.480599,0.572873,19.199716,210,212,0.952381,0.469423,0.460035,-1.999945,761.447125,642.487457,755.587505,750.318646
CA_x,Tuolumne,31,26,-16.129032,0.565363,0.483388,-14.499546,69,56,-18.84058,1.258389,1.041144,-17.263775,761.447125,642.487457,755.587505,750.318646
CA_y,Ventura,553,634,14.647378,0.665471,0.744922,11.938988,552,595,7.789855,0.664268,0.699099,5.243465,761.447125,642.487457,755.587505,750.318646
CA_x,Yolo,138,152,10.144928,0.682891,0.703837,3.067282,124,144,16.129032,0.613612,0.666793,8.666863,761.447125,642.487457,755.587505,750.318646
CA_y,Yuba,31,29,-6.451613,0.427521,0.385715,-9.778718,23,27,17.391304,0.317193,0.359114,13.216212,761.447125,642.487457,755.587505,750.318646

In [11]:
# Save fast food merged data to CSV
fast_food_data.to_csv("data/fast_food_combined_data.csv", index=False)

In [12]:
new_fast_food_data = fast_food_data.iloc[:,0:7]
new_fast_food_data[["Fast-food restaurants/1,000 pop, 2011", "Fast-food restaurants (% change), 2011-16", "Fast-food restaurants/1,000 pop, 2016", "Fast-food restaurants/1,000 pop (% change), 2011-16"]] = new_fast_food_data[["Fast-food restaurants/1,000 pop, 2011", "Fast-food restaurants (% change), 2011-16", "Fast-food restaurants/1,000 pop, 2016", "Fast-food restaurants/1,000 pop (% change), 2011-16"]].astype(float)
new_fast_food_data[["Fast-food restaurants, 2011", "Fast-food restaurants, 2016"]] = new_fast_food_data[["Fast-food restaurants, 2011", "Fast-food restaurants, 2016"]].astype(int)
new_fast_food_data["Fast-food restaurants/1,000 pop, 2011"] = [10 * val for val in new_fast_food_data["Fast-food restaurants/1,000 pop, 2011"]]
new_fast_food_data["Fast-food restaurants/1,000 pop, 2016"] = [10 * val for val in new_fast_food_data["Fast-food restaurants/1,000 pop, 2016"]]
new_fast_food_data = new_fast_food_data.rename(columns={"Fast-food restaurants/1,000 pop, 2011": "Fast-food restaurants/10,000 pop, 2011"})
new_fast_food_data = new_fast_food_data.rename(columns={"Fast-food restaurants/1,000 pop, 2016": "Fast-food restaurants/10,000 pop, 2016"})
new_fast_food_data.to_csv("data/new_fast_food_combined_data.csv", index=False)
new_fast_food_data

/opt/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py:3065: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

State,County,"Fast-food restaurants, 2011","Fast-food restaurants, 2016","Fast-food restaurants (% change), 2011-16","Fast-food restaurants/10,000 pop, 2011","Fast-food restaurants/10,000 pop, 2016","Fast-food restaurants/1,000 pop (% change), 2011-16"
CA_x,Alameda,1090,1293,18.623853,7.11388,7.82102,9.940291
CA_y,Alpine,2,0,-100.000000,18.29826,0.00000,-100.000000
CA_x,Amador,12,21,75.000000,3.19668,5.60403,75.308222
CA_y,Butte,147,158,7.482993,6.68173,6.97495,4.388394
CA_x,Calaveras,26,30,15.384615,5.75692,6.62032,14.997581
CA_y,Colusa,16,8,-50.000000,7.48853,3.69600,-50.644491
CA_x,Contra Costa,599,701,17.028381,5.61818,6.15644,9.580732
CA_y,Del Norte,15,10,-33.333333,5.27296,3.64299,-30.911961
CA_x,El Dorado,97,110,13.402062,5.35986,5.90534,10.177258
CA_y,Fresno,569,634,11.423550,6.05087,6.47247,6.967445
CA_x,Glenn,12,15,25.000000,4.26136,5.36346,25.862624
CA_y,Humboldt,95,97,2.105263,7.02460,7.10888,1.199816
CA_x,Imperial,81,103,27.160494,4.59817,5.69124,23.771749
CA_y,Inyo,13,15,15.384615,7.06483,8.31762,17.732744
CA_x,Kern,528,603,14.204545,6.22079,6.81290,9.518227
CA_y,Kings,90,89,-1.111111,5.91988,5.94137,0.363010
CA_x,Lake,30,33,10.000000,4.66759,5.16028,10.555590
CA_y,Lassen,13,15,15.384615,3.79629,4.84747,27.689722
CA_x,Los Angeles,7211,8264,14.602690,7.29415,8.14142,11.615733
CA_y,Madera,75,78,4.000000,4.93824,5.03336,1.926255
CA_x,Marin,171,189,10.526316,6.69263,7.22665,7.979239
CA_y,Mariposa,9,8,-11.111111,4.95213,4.56517,-7.814045
CA_x,Mendocino,52,54,3.846154,5.95190,6.16375,3.559302
CA_y,Merced,127,143,12.598425,4.89201,5.31840,8.715995
CA_x,Modoc,7,3,-57.142857,7.35681,3.35533,-54.391487
CA_y,Mono,18,21,16.666667,12.56194,14.89256,18.553058
CA_x,Monterey,246,264,7.317073,5.84098,6.05001,3.578610
CA_y,Napa,76,82,7.894737,5.51104,5.78896,5.042914
CA_x,Nevada,53,65,22.641509,5.36905,6.56214,22.221780
CA_y,Orange,2575,3025,17.475728,8.43304,9.51945,12.882804
CA_x,Placer,274,334,21.897810,7.68702,8.79545,14.419435
CA_y,Plumas,13,9,-30.769231,6.59363,4.79055,-27.345832
CA_x,Riverside,1331,1541,15.777611,5.95289,6.45710,8.469984
CA_y,Sacramento,937,1075,14.727855,6.53187,7.10387,8.757118
CA_x,San Benito,26,28,7.692308,4.64004,4.71897,1.701033
CA_y,San Bernardino,1346,1526,13.372957,6.52644,7.14041,9.407534
CA_x,San Diego,2348,2736,16.524702,7.47826,8.24792,10.291937
CA_y,San Francisco,753,958,27.224436,9.22462,10.93479,18.539194
CA_x,San Joaquin,401,466,16.209476,5.76919,6.34623,10.002039
CA_y,San Luis Obispo,219,234,6.849315,8.07671,8.28958,2.635633
CA_x,San Mateo,501,593,18.363273,6.87222,7.70569,12.128123
CA_y,Santa Barbara,286,344,20.279720,6.71270,7.70789,14.825446
CA_x,Santa Clara,1288,1544,19.875776,7.10107,7.99348,12.567269
CA_y,Santa Cruz,171,175,2.339181,6.45032,6.35910,-1.414178
CA_x,Shasta,133,122,-8.270677,7.48895,6.82426,-8.875624
CA_y,Sierra,1,1,0.000000,3.22581,3.37382,4.588394
CA_x,Siskiyou,29,28,-3.448276,6.50020,6.43515,-1.000698
CA_y,Solano,270,290,7.407407,6.48023,6.58615,1.634526
CA_x,Sonoma,273,291,6.593407,5.59630,5.77572,3.206040
CA_y,Stanislaus,327,366,11.926606,6.31233,6.76084,7.105322
CA_x,Sutter,51,59,15.686275,5.39340,6.14212,13.882177
CA_y,Tehama,34,33,-2.941176,5.36726,5.20144,-3.089570
CA_x,Trinity,12,6,-50.000000,8.77385,4.67326,-46.736506
CA_y,Tulare,215,264,22.790698,4.80599,5.72873,19.199716
CA_x,Tuolumne,31,26,-16.129032,5.65363,4.83388,-14.499546
CA_y,Ventura,553,634,14.647378,6.65471,7.44922,11.938988
CA_x,Yolo,138,152,10.144928,6.82891,7.03837,3.067282
CA_y,Yuba,31,29,-6.451613,4.27521,3.85715,-9.778718

## Combine Census Data

In [13]:
# Read Census data for 2011 and 2016
census_2011 = pd.read_csv("data/census_data_2011.csv")
census_2016 = pd.read_csv("data/census_data_2016.csv")

In [14]:
# Merge Census data
census_data = census_2011.merge(census_2016, how="outer", on="County")
census_data.head()

,County,Household Income_x,Population_x,Median Age_x,Per Capita Income_x,Poverty Count_x,Employed Persons Over 16_x,Unemployed Persons Over 16_x,Household Income_y,Population_y,Median Age_y,Per Capita Income_y,Poverty Count_y,Employed Persons Over 16_y,Unemployed Persons Over 16_y
0,Alameda,70821.0,1494876.0,36.4,34937.0,173156.0,792734.0,401593.0,79831.0,1605217.0,37.2,39042.0,189590.0,864007.0,434239.0
1,Alpine,59018.0,1167.0,40.4,29576.0,170.0,581.0,351.0,62375.0,1184.0,42.8,26783.0,221.0,468.0,499.0
2,Amador,56180.0,38244.0,48.0,28030.0,3372.0,15650.0,17192.0,57032.0,36963.0,50.3,27496.0,3684.0,14540.0,17341.0
3,Butte,42971.0,219309.0,37.2,23431.0,42283.0,101633.0,77585.0,44366.0,223877.0,36.9,25077.0,46456.0,102069.0,81862.0
4,Calaveras,55256.0,45794.0,49.0,28667.0,3751.0,20270.0,17987.0,53502.0,44787.0,51.2,30577.0,5641.0,18329.0,19512.0

In [15]:
# Fix column names
census_data = census_data.rename(columns={"Household Income_x": "Household Income 2011",
                                          "Population_x": "Population 2011",
                                          "Median Age_x": "Median Age 2011",
                                          "Per Capita Income_x": "Per Capita Income 2011",
                                          "Poverty Count_x": "Poverty Count 2011",
                                          "Employed Persons Over 16_x": "Employed Persons Over 16 2011",
                                          "Unemployed Persons Over 16_x": "Unemployed Persons Over 16 2011",
                                          "Household Income_y": "Household Income 2016",
                                          "Population_y": "Population 2016",
                                          "Median Age_y": "Median Age 2016",
                                          "Per Capita Income_y": "Per Capita Income 2016",
                                          "Poverty Count_y": "Poverty Count 2016",
                                          "Employed Persons Over 16_y": "Employed Persons Over 16 2016",
                                          "Unemployed Persons Over 16_y": "Unemployed Persons Over 16 2016"})
census_data.head()

,County,Household Income 2011,Population 2011,Median Age 2011,Per Capita Income 2011,Poverty Count 2011,Employed Persons Over 16 2011,Unemployed Persons Over 16 2011,Household Income 2016,Population 2016,Median Age 2016,Per Capita Income 2016,Poverty Count 2016,Employed Persons Over 16 2016,Unemployed Persons Over 16 2016
0,Alameda,70821.0,1494876.0,36.4,34937.0,173156.0,792734.0,401593.0,79831.0,1605217.0,37.2,39042.0,189590.0,864007.0,434239.0
1,Alpine,59018.0,1167.0,40.4,29576.0,170.0,581.0,351.0,62375.0,1184.0,42.8,26783.0,221.0,468.0,499.0
2,Amador,56180.0,38244.0,48.0,28030.0,3372.0,15650.0,17192.0,57032.0,36963.0,50.3,27496.0,3684.0,14540.0,17341.0
3,Butte,42971.0,219309.0,37.2,23431.0,42283.0,101633.0,77585.0,44366.0,223877.0,36.9,25077.0,46456.0,102069.0,81862.0
4,Calaveras,55256.0,45794.0,49.0,28667.0,3751.0,20270.0,17987.0,53502.0,44787.0,51.2,30577.0,5641.0,18329.0,19512.0

In [16]:
# Read health and fast food
health_ff = pd.read_csv("data/big_df.csv")
health_ff.head()

,County,"Fast-food restaurants, 2011","Fast-food restaurants, 2016","Fast-food restaurants (% change), 2011-16","Fast-food restaurants/10,000 pop, 2011","Fast-food restaurants/10,000 pop, 2016","Fast-food restaurants/1,000 pop (% change), 2011-16",Obesity 2011 %,Obesity 2016 %,New Diabetes per 1k : 2011,New Diabetes per 1k : 2016,Diagnosed Diabetes 2011 %,Diagnosed Diabetes 2016 %
0,Alameda,1090,1293,18.623853,7.11388,7.82102,9.940291,20.2,19.2,7.3,5.6,7.7,6.7
1,Alpine,2,0,-100.000000,18.29826,0.00000,-100.000000,22.6,20.9,8.4,4.1,8.0,4.6
2,Amador,12,21,75.000000,3.19668,5.60403,75.308222,24.8,29.8,8.3,10.1,7.8,10.4
3,Butte,147,158,7.482993,6.68173,6.97495,4.388394,24.2,27.2,9.0,8.0,8.6,8.7
4,Calaveras,26,30,15.384615,5.75692,6.62032,14.997581,23.9,30.4,7.6,7.9,7.4,8.3

In [17]:
# Merge Census data with health and fast food data
census_health_ff = census_data.merge(health_ff, how="outer", on="County")
census_health_ff.head()

,County,Household Income 2011,Population 2011,Median Age 2011,Per Capita Income 2011,Poverty Count 2011,Employed Persons Over 16 2011,Unemployed Persons Over 16 2011,Household Income 2016,Population 2016,...,"Fast-food restaurants (% change), 2011-16","Fast-food restaurants/10,000 pop, 2011","Fast-food restaurants/10,000 pop, 2016","Fast-food restaurants/1,000 pop (% change), 2011-16",Obesity 2011 %,Obesity 2016 %,New Diabetes per 1k : 2011,New Diabetes per 1k : 2016,Diagnosed Diabetes 2011 %,Diagnosed Diabetes 2016 %
0,Alameda,70821.0,1494876.0,36.4,34937.0,173156.0,792734.0,401593.0,79831.0,1605217.0,...,18.623853,7.11388,7.82102,9.940291,20.2,19.2,7.3,5.6,7.7,6.7
1,Alpine,59018.0,1167.0,40.4,29576.0,170.0,581.0,351.0,62375.0,1184.0,...,-100.000000,18.29826,0.00000,-100.000000,22.6,20.9,8.4,4.1,8.0,4.6
2,Amador,56180.0,38244.0,48.0,28030.0,3372.0,15650.0,17192.0,57032.0,36963.0,...,75.000000,3.19668,5.60403,75.308222,24.8,29.8,8.3,10.1,7.8,10.4
3,Butte,42971.0,219309.0,37.2,23431.0,42283.0,101633.0,77585.0,44366.0,223877.0,...,7.482993,6.68173,6.97495,4.388394,24.2,27.2,9.0,8.0,8.6,8.7
4,Calaveras,55256.0,45794.0,49.0,28667.0,3751.0,20270.0,17987.0,53502.0,44787.0,...,15.384615,5.75692,6.62032,14.997581,23.9,30.4,7.6,7.9,7.4,8.3

In [18]:
# Export data to CSV
census_health_ff.to_csv("data/census_health_ff_2011_2016.csv", index=False)

In [2]:
# Read main data and education data to merge the data sets
census_health_ff = pd.read_csv("data/census_health_ff_2011_2016.csv")
education_2012 = pd.read_csv("data/census_education_data_2012.csv")
education_2016 = pd.read_csv("data/census_education_data_2016.csv")

# Merge education data first
education_data = education_2012.merge(education_2016, how="outer", on="County")
education_data.head()

,County,Population_x,No Education_x,High School Education_x,GED education_x,Associate Education_x,Bachelor Education_x,Masters Education_x,Professional Education_x,Doctorate Education_x,...,No Education_y,High School Education_y,GED education_y,Associate Education_y,Bachelor Education_y,Masters Education_y,Professional Education_y,Doctorate Education_y,College_y,College Rate_y
0,Alameda,1515136.0,21320.0,183121.0,16511.0,69629.0,249246.0,116816.0,27561.0,27987.0,...,26836.0,182207.0,18164.0,74447.0,282754.0,141689.0,32639.0,31512.0,563041.0,35.075694
1,Alpine,1197.0,0.0,153.0,58.0,49.0,142.0,76.0,14.0,22.0,...,5.0,189.0,68.0,46.0,140.0,67.0,8.0,20.0,281.0,23.733108
2,Amador,37764.0,198.0,7117.0,938.0,2802.0,4042.0,825.0,417.0,138.0,...,279.0,6562.0,1131.0,2554.0,4212.0,1192.0,540.0,240.0,8738.0,23.639856
3,Butte,220101.0,2273.0,27686.0,4560.0,12955.0,22359.0,7246.0,2598.0,1585.0,...,2749.0,27537.0,5238.0,14030.0,25225.0,8002.0,2915.0,1611.0,51783.0,23.130112
4,Calaveras,45507.0,87.0,8778.0,1186.0,3234.0,4988.0,1373.0,513.0,142.0,...,310.0,8057.0,1158.0,3692.0,4645.0,1550.0,424.0,226.0,10537.0,23.526916

In [3]:
# Drop population columns, rename for years
education_data = education_data.rename(columns={"No Education_x": "No Education 2012",
                                            "Population_x": "Population 2012",
                                          "High School Education_x": "High School Education 2012",
                                          "GED education_x": "GED education 2012",
                                          "Associate Education_x": "Associate Education 2012",
                                          "Bachelor Education_x": "Bachelor Education 2012",
                                          "Masters Education_x": "Masters Education 2012",
                                          "Professional Education_x": "Professional Education 2012",
                                          "Doctorate Education_x": "Doctorate Education 2012",
                                          "College_x": "College 2012",
                                          "College Rate_x": "College Rate 2012",
                                          "No Education_y": "No Education 2016",
                                          "High School Education_y": "High School Education 2016",
                                          "GED education_y": "GED education 2016",
                                          "Associate Education_y": "Associate Education 2016",
                                          "Bachelor Education_y": "Bachelor Education 2016",
                                          "Masters Education_y": "Masters Education 2016",
                                          "Professional Education_y": "Professional Education 2016",
                                          "College_y": "College 2016",
                                          "College Rate_y": "College Rate 2016",
                                               "Doctorate Education_y": "Doctorate Education 2016"})
education_data.head()

,County,Population 2012,No Education 2012,High School Education 2012,GED education 2012,Associate Education 2012,Bachelor Education 2012,Masters Education 2012,Professional Education 2012,Doctorate Education 2012,...,No Education 2016,High School Education 2016,GED education 2016,Associate Education 2016,Bachelor Education 2016,Masters Education 2016,Professional Education 2016,Doctorate Education 2016,College 2016,College Rate 2016
0,Alameda,1515136.0,21320.0,183121.0,16511.0,69629.0,249246.0,116816.0,27561.0,27987.0,...,26836.0,182207.0,18164.0,74447.0,282754.0,141689.0,32639.0,31512.0,563041.0,35.075694
1,Alpine,1197.0,0.0,153.0,58.0,49.0,142.0,76.0,14.0,22.0,...,5.0,189.0,68.0,46.0,140.0,67.0,8.0,20.0,281.0,23.733108
2,Amador,37764.0,198.0,7117.0,938.0,2802.0,4042.0,825.0,417.0,138.0,...,279.0,6562.0,1131.0,2554.0,4212.0,1192.0,540.0,240.0,8738.0,23.639856
3,Butte,220101.0,2273.0,27686.0,4560.0,12955.0,22359.0,7246.0,2598.0,1585.0,...,2749.0,27537.0,5238.0,14030.0,25225.0,8002.0,2915.0,1611.0,51783.0,23.130112
4,Calaveras,45507.0,87.0,8778.0,1186.0,3234.0,4988.0,1373.0,513.0,142.0,...,310.0,8057.0,1158.0,3692.0,4645.0,1550.0,424.0,226.0,10537.0,23.526916

In [4]:
education_data = education_data.drop(columns=["Population_y"])
education_data.count()

County                         58
Population 2012                58
No Education 2012              58
High School Education 2012     58
GED education 2012             58
Associate Education 2012       58
Bachelor Education 2012        58
Masters Education 2012         58
Professional Education 2012    58
Doctorate Education 2012       58
College 2012                   58
College Rate 2012              58
No Education 2016              58
High School Education 2016     58
GED education 2016             58
Associate Education 2016       58
Bachelor Education 2016        58
Masters Education 2016         58
Professional Education 2016    58
Doctorate Education 2016       58
College 2016                   58
College Rate 2016              58
dtype: int64

In [5]:
# Merge education data with larger dataset
census_health_ff_education = census_health_ff.merge(education_data, how="outer", on="County")
census_health_ff_education.count()

County                                                 58
Household Income 2011                                  58
Population 2011                                        58
Median Age 2011                                        58
Per Capita Income 2011                                 58
Poverty Count 2011                                     58
Employed Persons Over 16 2011                          58
Unemployed Persons Over 16 2011                        58
Household Income 2016                                  58
Population 2016                                        58
Median Age 2016                                        58
Per Capita Income 2016                                 58
Poverty Count 2016                                     58
Employed Persons Over 16 2016                          58
Unemployed Persons Over 16 2016                        58
Fast-food restaurants, 2011                            58
Fast-food restaurants, 2016                            58
Fast-food restaurants (% change), 2011-16              58
Fast-food restaurants/10,000 pop, 2011                 58
Fast-food restaurants/10,000 pop, 2016                 58
Fast-food restaurants/1,000 pop (% change), 2011-16    58
Obesity 2011 %                                         58
Obesity 2016 %                                         58
New Diabetes per 1k : 2011                             58
New Diabetes per 1k : 2016                             58
Diagnosed Diabetes 2011 %                              58
Diagnosed Diabetes 2016 %                              58
Population 2012                                        58
No Education 2012                                      58
High School Education 2012                             58
GED education 2012                                     58
Associate Education 2012                               58
Bachelor Education 2012                                58
Masters Education 2012                                 58
Professional Education 2012                            58
Doctorate Education 2012                               58
College 2012                                           58
College Rate 2012                                      58
No Education 2016                                      58
High School Education 2016                             58
GED education 2016                                     58
Associate Education 2016                               58
Bachelor Education 2016                                58
Masters Education 2016                                 58
Professional Education 2016                            58
Doctorate Education 2016                               58
College 2016                                           58
College Rate 2016                                      58
dtype: int64

In [6]:
# Export to CSV
census_health_ff_education.to_csv("data/census_health_ff_education.csv", index=False)